[project]
name = "riffscribe-django"
version = "0.1.0"
description = "Convert audio to guitar tabs with AI - Django + HTMX version"
readme = "README.md"
authors = [
    { name = "abdul hamid", email = "abdulachik@icloud.com" }
]
requires-python = ">=3.11"
dependencies = [
    "django>=5.0",
    "django-htmx>=1.17",
    "pillow>=10.0",
    "numpy>=1.26",
    "scipy>=1.11",
    "librosa>=0.10",
    "pretty-midi>=0.2",
    "pydub>=0.25",
    "whitenoise>=6.6",
    "python-decouple>=3.8",
]

[project.optional-dependencies]
dev = [
    "django-debug-toolbar>=4.2",
    "pytest>=7.4",
    "pytest-django>=4.7",
    "black>=23.12",
    "ruff>=0.1",
]

[build-system]
requires = ["uv_build>=0.8.15,<0.9.0"]
build-backend = "uv_build"
