# Generated by Django 5.2.6 on 2025-09-04 23:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('original_audio', models.FileField(blank=True, null=True, upload_to='audio/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('sample_rate', models.IntegerField(blank=True, null=True)),
                ('channels', models.IntegerField(default=1)),
                ('estimated_tempo', models.IntegerField(blank=True, null=True)),
                ('estimated_key', models.CharField(blank=True, max_length=20)),
                ('complexity', models.CharField(blank=True, choices=[('simple', 'Simple'), ('moderate', 'Moderate'), ('complex', 'Complex')], max_length=20)),
                ('detected_instruments', models.JSONField(blank=True, default=list)),
                ('midi_data', models.JSONField(blank=True, null=True)),
                ('musicxml_content', models.TextField(blank=True)),
                ('gp5_file', models.FileField(blank=True, null=True, upload_to='gp5/%Y/%m/%d/')),
                ('guitar_notes', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TabExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('musicxml', 'MusicXML'), ('gp5', 'Guitar Pro 5'), ('pdf', 'PDF'), ('ascii', 'ASCII Tab')], max_length=20)),
                ('file', models.FileField(upload_to='exports/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='transcriber.transcription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
