# Generated by Django 5.2.6 on 2025-09-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transcriber", "0002_add_playability_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcription",
            name="whisper_analysis",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
