# Generated by Django 5.2.6 on 2025-09-05 03:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transcriber", "0003_add_whisper_analysis"),
    ]

    operations = [
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "track_type",
                    models.CharField(
                        choices=[
                            ("drums", "Drums"),
                            ("bass", "Bass"),
                            ("vocals", "Vocals"),
                            ("other", "Other/Accompaniment"),
                            ("original", "Original Mix"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "instrument_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("drums", "Drums"),
                            ("bass", "Bass Guitar"),
                            ("electric_guitar", "Electric Guitar"),
                            ("acoustic_guitar", "Acoustic Guitar"),
                            ("vocals", "Vocals"),
                            ("piano", "Piano"),
                            ("strings", "Strings"),
                            ("synthesizer", "Synthesizer"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("track_name", models.CharField(blank=True, max_length=100)),
                ("track_order", models.IntegerField(default=0)),
                (
                    "separated_audio",
                    models.FileField(
                        blank=True, null=True, upload_to="tracks/%Y/%m/%d/"
                    ),
                ),
                ("volume_level", models.FloatField(blank=True, null=True)),
                ("prominence_score", models.FloatField(blank=True, null=True)),
                ("midi_data", models.JSONField(blank=True, null=True)),
                ("guitar_notes", models.JSONField(blank=True, null=True)),
                ("chord_progressions", models.JSONField(blank=True, null=True)),
                ("is_processed", models.BooleanField(default=False)),
                ("processing_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transcription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="transcriber.transcription",
                    ),
                ),
            ],
            options={
                "ordering": ["track_order", "track_type"],
                "unique_together": {("transcription", "track_type")},
            },
        ),
        migrations.CreateModel(
            name="MultiTrackExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("musicxml", "MusicXML (Multi-track)"),
                            ("gp5", "Guitar Pro 5 (Multi-track)"),
                            ("midi", "MIDI (Multi-track)"),
                            ("stems", "Audio Stems (ZIP)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="multi_exports/%Y/%m/%d/")),
                ("export_settings", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transcription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multi_exports",
                        to="transcriber.transcription",
                    ),
                ),
                (
                    "included_tracks",
                    models.ManyToManyField(
                        related_name="exports", to="transcriber.track"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrackVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variant_name",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("balanced", "Balanced"),
                            ("technical", "Technical"),
                            ("original", "Original"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "difficulty_score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "playability_score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("tab_data", models.JSONField()),
                ("removed_techniques", models.JSONField(blank=True, null=True)),
                ("config", models.JSONField(blank=True, null=True)),
                ("is_selected", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="transcriber.track",
                    ),
                ),
            ],
            options={
                "ordering": ["difficulty_score"],
                "unique_together": {("track", "variant_name")},
            },
        ),
    ]
