# Generated by Django 5.2.6 on 2025-09-05 03:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transcriber", "0004_add_multi_track_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transcription",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transcriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
                (
                    "skill_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                ("preferred_genres", models.JSONField(blank=True, default=list)),
                ("github_username", models.CharField(blank=True, max_length=100)),
                ("github_profile_url", models.URLField(blank=True)),
                ("google_profile_url", models.URLField(blank=True)),
                (
                    "default_tempo_adjustment",
                    models.FloatField(
                        default=1.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.5),
                            django.core.validators.MaxValueValidator(2.0),
                        ],
                    ),
                ),
                (
                    "preferred_difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("balanced", "Balanced"),
                            ("technical", "Technical"),
                            ("original", "Original"),
                        ],
                        default="balanced",
                        max_length=20,
                    ),
                ),
                ("transcriptions_count", models.IntegerField(default=0)),
                ("total_duration_processed", models.FloatField(default=0.0)),
                ("is_premium", models.BooleanField(default=False)),
                ("monthly_upload_limit", models.IntegerField(default=10)),
                ("uploads_this_month", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "favorite_transcriptions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="favorited_by",
                        to="transcriber.transcription",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
