# Generated by Django 5.2.6 on 2025-09-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transcriber", "0006_userprofile_comments_received_downvotes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcription",
            name="is_public",
            field=models.BooleanField(
                default=False, help_text="Allow public access to this transcription"
            ),
        ),
    ]
