# Generated by Django 5.2.6 on 2025-09-17 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transcriber", "0007_transcription_is_public"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="confidence_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transcription",
            name="accuracy_score",
            field=models.FloatField(
                blank=True, help_text="Estimated accuracy (0-1)", null=True
            ),
        ),
        migrations.AddField(
            model_name="transcription",
            name="commercial_license",
            field=models.BooleanField(
                default=False, help_text="Can be used commercially"
            ),
        ),
        migrations.AddField(
            model_name="transcription",
            name="export_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="transcription",
            name="last_viewed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transcription",
            name="models_used",
            field=models.JSONField(
                blank=True, default=list, help_text="List of AI models used"
            ),
        ),
        migrations.AddField(
            model_name="transcription",
            name="multitrack_data",
            field=models.JSONField(
                blank=True, help_text="Combined multi-track analysis results", null=True
            ),
        ),
        migrations.AddField(
            model_name="transcription",
            name="processing_model_version",
            field=models.CharField(default="advanced_v2.0", max_length=50),
        ),
        migrations.AddField(
            model_name="transcription",
            name="separated_stems",
            field=models.JSONField(
                blank=True, help_text="Paths to separated audio stems", null=True
            ),
        ),
        migrations.AddField(
            model_name="transcription",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_export",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_use_api",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_use_commercial",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="subscription_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="subscription_tier",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("premium", "Premium"),
                    ("professional", "Professional"),
                ],
                default="free",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="monthly_upload_limit",
            field=models.IntegerField(default=3),
        ),
        migrations.CreateModel(
            name="ConversionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("viewed_transcription", "Viewed Transcription"),
                            ("attempted_export", "Attempted Export"),
                            ("signed_up", "Signed Up"),
                            ("upgraded_premium", "Upgraded to Premium"),
                            ("cancelled_subscription", "Cancelled Subscription"),
                            ("used_feature", "Used Feature"),
                        ],
                        max_length=50,
                    ),
                ),
                ("feature_name", models.CharField(blank=True, max_length=100)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transcription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transcriber.transcription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="transcriber_event_t_32e9d0_idx",
                    ),
                    models.Index(
                        fields=["user", "event_type"],
                        name="transcriber_user_id_53490d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UsageAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("transcriptions_created", models.IntegerField(default=0)),
                ("exports_attempted", models.IntegerField(default=0)),
                ("exports_completed", models.IntegerField(default=0)),
                ("total_processing_time", models.FloatField(default=0.0)),
                ("features_used", models.JSONField(blank=True, default=list)),
                ("avg_accuracy_score", models.FloatField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
